//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Achevement
    {
        public string user_id { get; set; }
        public int badge_id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
    
        public virtual Badge Badge { get; set; }
        public virtual AspNetUser AspNetUser { get; set; }
    }
}
