//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Badge
    {
        public Badge()
        {
            this.Achevements = new HashSet<Achevement>();
        }
    
        public int id { get; set; }
        public string img_src { get; set; }
        public string description { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Achevement> Achevements { get; set; }
    }
}
