//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DbContextGame : DbContext
    {
        public DbContextGame()
            : base("name=DbContextGame")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Achevement> Achevements { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<Badge> Badges { get; set; }
        public virtual DbSet<Image> Images { get; set; }
        public virtual DbSet<Level> Levels { get; set; }
        public virtual DbSet<Score> Scores { get; set; }
        public virtual DbSet<Type_Images> Type_Images { get; set; }
    }
}
