//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;
    
    public partial class Level
    {
        public int id { get; set; }
        public int type_img { get; set; }
        public int score { get; set; }
    
        public virtual Type_Images Type_Images { get; set; }
    }
}
