//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project
{
    using System;
    using System.Collections.Generic;

    public partial class Score : IComparable<Score>
    {
        public string user_id { get; set; }
        public System.DateTime date_scored { get; set; }
        public int score1 { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }

        public int CompareTo(Score score)
        {
   
            return score.score1.CompareTo(this.score1);
        }
    }
}
